<div class="container col s4" id="postContainer" style="height:400px; overflow:auto;">
	<div class="row">

	</div>
	<div id="bottom"></div>
</div>

<?php echo $this->form()->openTag($form); ?>

<div class="input-group">
	<?php echo $this->formInput($form->get('textfield')); ?>
	<?php echo $this->formElementErrors($form->get('textfield'), array('class'=>'alert alert-danger')); ?>
	<span class="input-group-addon">
		<?php echo $this->formRow($form->get('submit'));?>
	</span>
</div>

<?php echo $this->form()->closeTag();?>

<script>
	var id = <?php echo $user; ?>
</script
