<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'login',
		array(
			'action'		=> 'index',
			'autocomplete'	=> 'off',
			'process'		=> 'process',
		)
	));
	$form->prepare();
?>


<?php echo $this->form()->openTag($form); ?>

	<!-- Form Name -->
	<legend>Login</legend>

	<!-- Text input-->
	<div class="control-group">
		<label class="control-label" for="firstName">Firstname</label>
		<div class="controls">
			<?php echo $this->formInput($form->get('firstname')); ?>
			<?php echo $this->formElementErrors($form->get('firstname'), array('class'=>'error')); ?>
		</div>
	</div>

	<!-- Text input-->
	<div class="control-group">
		<label class="control-label" for="lastName">Lastname</label>
		<div class="controls">
			<?php echo $this->formInput($form->get('lastname')); ?>
			<?php echo $this->formElementErrors($form->get('lastname'), array('class'=>'error')); ?>
		</div>
	</div>

	<!-- Button -->
	<div class="control-group">
		<label class="control-label" for="submit"></label>
		<div class="controls">
			<?php echo $this->formRow($form->get('submit'));?>
		</div>
	</div>

<?php echo $this->form()->closeTag();?>





