<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url(
		'login',
		array(
			'action'		=> 'index',
			'autocomplete'	=> 'off',
			'process'		=> 'process',
		)
	));
	$form->prepare();
?>

<div class="row">
	<?php echo $this->form()->openTag($form); ?>
		<div class="row">
			<div class="input-field col s12">
				<?php echo $this->formInput($form->get('firstname')); ?>
				<label for="first_name">First Name</label>
				<?php echo $this->formElementErrors($form->get('firstname'), array('class'=>'card-panel red lighten-2 white-text col s5')); ?>
			</div>

			<div class="input-field col s12">
				<?php echo $this->formInput($form->get('lastname')); ?>
				<label for="last_name">Last Name</label>
				<?php echo $this->formElementErrors($form->get('lastname'), array('class'=>'card-panel red lighten-2 white-text col s5')); ?>
			</div>
		</div>
		<button class="btn waves-effect waves-light" type="submit" name="action">Submit
			<i class="mdi-content-send right"></i>
		</button>
	<?php echo $this->form()->closeTag();?>
</div>





