<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('ZF2'); ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
						->prependStylesheet($this->basePath('css/style.css'))
						->prependStylesheet($this->basePath('css/materialize.min.css'))
						->prependStylesheet($this->basePath('font/material-design-icons'))
						->prependStylesheet($this->basePath('font/roboto'))                        
						//->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
						//->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

		<!-- Scripts -->
		<?php echo $this->headScript()
			->prependFile($this->basePath('js/bootstrap.min.js'))
			->prependFile($this->basePath('js/script.js'))
			->prependFile($this->basePath('js/materialize.min.js'))
			->prependFile($this->basePath('js/jquery.min.js'))
			->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
		; ?>

	</head>
	<body>
	<nav class="red lighten-1">
			<div class="nav-wrapper">
				<div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Logo</a>
				<a href="#" data-activates="mobile-nav" class="right button-collapse"><i class="mdi-navigation-more-vert"></i></a>
			</div>
		</nav>
		<div class="container">
			<?php echo $this->content; ?>
			<footer>
			   
			</footer>
		</div> <!-- /container -->
		<?php echo $this->inlineScript() ?>
	</body>
</html>
