<script>var pics = []; </script>

<div class="row">

<?php $i = 1; foreach ($pictures as $picture) { ?>

	<div class="col s8 m7 l6" id="card_<?= $i;?>">
		<div class="card" style="overflow:visible;">
			<div class="card-image">
			</div>
			<div class="card-content">
			</div>
			<div class="card-action">
				<a href="#">This is a link</a>
				<a href='#'>This is a link</a>
			</div>
		</div>
	</div>


	<script>
		 pics.push({
				"image": "<?= $picture->image ?>",
				"title": "<?= $picture->title ?>",
				"desc":  "<?= $picture->description ?>"
			}
		);
	</script>
<?php $i++;
}?>
</div>
<ul class="pagination">
<?php $pages = round(($i / 4), 0, PHP_ROUND_HALF_UP);
		for ($i=1; $i <= $pages; $i++) { 
			echo "<a href='#" . $i . "' onclick='paginationBtn(" . $i . ")'><li class='waves-effect pag' id='pag_" . $i . "'>" . $i . "</li></a>";
		}
?>

</ul>