
<div class="row">
<?php for ($i=0; $i < 6; $i++) { ?>
	<div class="col s8 m7 l6">
		<div class="card" style="overflow:visible;">
			<div class="card-image">
				<img class="materialboxed s12 m12 l12" src="/img/tigre.jpg">
				<span class="card-title">Card Title</span>
			</div>
			<div class="card-content">
				<p>I am a very simple card. I am good at containing small bits of information.
				I am convenient because I require little markup to use effectively.</p>
			</div>
			<div class="card-action">
				<a href="#">This is a link</a>
				<a href='#'>This is a link</a>
			</div>
		</div>
	</div>
<?php }?>
</div>
