
<div class="row">
<?php foreach ($pictures as $picture) { ?>
	<div class="col s8 m7 l6">
		<div class="card" style="overflow:visible;">
			<div class="card-image">
				<img class="materialboxed s12 m12 l12" src="img/<?= $picture->image?>">
				<span class="card-title"><?= $picture->title?></span>
			</div>
			<div class="card-content">
				<p><?= $picture->description?></p>
			</div>
			<div class="card-action">
				<a href="#">This is a link</a>
				<a href='#'>This is a link</a>
			</div>
		</div>
	</div>
<?php }?>
</div>
